version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=caboose.proxy.rlwy.net:46591
      - PMA_PORT=46591
      - PMA_USER=root
      - PMA_PASSWORD=cfRhvVNsmvilrwODMjaixIlzTzfCbPMg